[package]
name = "zeronet_tracker"
version = "0.1.0"
authors = ["Ansho Rei <anshorei@zeroid.bit>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeronet_protocol = { path = "../zeronet_protocol" }
log = "*"
pretty_env_logger = "*"
futures = "*"
serde_json = "*"
